// The launch social kit as Markdown, for docs/launch/social-kit.md.
// Every line comes from ./beats and ./facts; edit those, not the output.
import { xPostLength } from "@hraness/design-kit/launch";
import { LAUNCH_BEATS, LAUNCH_SOCIAL_KIT as kit } from "./beats.ts";
import { LAUNCH_FACTS, LAUNCH_RELEASE } from "./facts.ts";

const block = (text: string): string => ["```text", text, "```"].join("\n");
const thread = (name: string, posts: readonly string[], count: (post: string) => number): string[] => [
  `## ${name}`,
  "",
  ...posts.flatMap((post, index) => [`Post ${index + 1} of ${posts.length}, ${count(post)} characters`, "", block(post), ""]),
];
const chars = (post: string) => [...post].length;

export function renderSocialKitMarkdown(): string {
  return [
    "# Clankdar launch social kit",
    "",
    "Generated by `bun run launch:kit` from `site/launch/beats.ts` and `site/launch/facts.ts`. Do not edit by hand; change the beats or facts and run it again.",
    "",
    `Posts go out from the @hraness account. The status is ${LAUNCH_RELEASE.status}: the demo runs from source and the hosted API is invitation-only staging, so no post asks anyone to install or sign up. Show HN and the Product Hunt first comment are written by a person from the fact sheet below.`,
    "",
    ...thread("X thread", kit.x, xPostLength),
    ...thread("Bluesky thread", kit.bluesky, chars),
    ...thread("Threads thread", kit.threads, chars),
    "## LinkedIn post",
    "",
    block(kit.linkedin),
    "",
    "## Product Hunt",
    "",
    `Tagline: ${kit.productHunt.tagline}`,
    "",
    "Description:",
    "",
    block(kit.productHunt.description),
    "",
    `Topics: ${kit.productHunt.tags.join(", ")}`,
    "",
    "## Show HN and first comment fact sheet",
    "",
    ...kit.showHnFacts.map(fact => `- ${fact}`),
    "",
    "## Beats",
    "",
    ...LAUNCH_BEATS.map((beat, index) => `${index + 1}. ${beat.headline}`),
    "",
    "## Facts and their records",
    "",
    ...Object.entries(LAUNCH_FACTS).map(([name, fact]) => `- ${name}: ${fact.value}. ${fact.source}`),
    "",
  ].join("\n");
}
