import { supportFooter } from "../../site/support-footer.ts";

/** Read-only HTML projections. JSON and signed evidence remain the source of truth. */
const escape = (value: unknown): string => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const count = (value: unknown): number => typeof value === "number" && Number.isSafeInteger(value) && value >= 0 ? value : 0;
const date = (value: unknown): string => typeof value === "string" && Number.isFinite(Date.parse(value)) ? new Date(value).toISOString().replace("T", " ").replace(".000Z", " UTC") : "Not yet";
const actorPath = (address: string) => `/actors/${encodeURIComponent(address)}`;
const campaignPath = (address: string, id: string) => `${actorPath(address)}/campaigns/${encodeURIComponent(id)}`;

function page(title: string, body: string): Response {
  return new Response(`<!doctype html>
<html lang="en" data-hraness-theme="paper" data-hraness-material="lantern" data-hraness-marketing-preset="editorial"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,follow"><meta name="color-scheme" content="light dark">
<title>${escape(title)} · Clankdar</title>
<link rel="icon" href="/icon.png"><link rel="stylesheet" href="/design/fonts.css"><link rel="stylesheet" href="/design/paper-theme.css"><link rel="stylesheet" href="/design/product-marketing-preset.css"><link rel="stylesheet" href="/design/lantern-material.css"><link rel="stylesheet" href="/design/appearance-menu.css"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/profile.css"><link rel="stylesheet" href="/footer.css"><script src="/appearance.js"></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><div class="page">
<header class="masthead"><a class="wordmark" href="https://clankdar.com"><img class="mark" src="/marks/clankdar.svg" alt="" width="24" height="24">clankdar</a><div class="header-actions"><nav class="site-nav" aria-label="Site"><a href="https://clankdar.com/docs/#hosted">Get started</a><a href="https://clankdar.com/benchmark/">Benchmark</a></nav><div class="hraness-design-theme-toggle" data-hraness-appearance-menu data-presentation="menu" data-ready="false"><button type="button" class="hraness-design-theme-toggle__trigger" aria-label="Appearance: System" aria-haspopup="menu" aria-expanded="false" aria-controls="appearance-menu"><span data-current-appearance-icon="system" aria-hidden="true">◐</span></button><div class="hraness-design-theme-toggle__popover" hidden><div class="hraness-design-theme-toggle__menu" id="appearance-menu" role="menu" aria-label="Appearance"><button class="hraness-design-theme-toggle__item" type="button" role="menuitemradio" aria-checked="false" data-theme-value="light"><span data-appearance-icon="light" aria-hidden="true"></span><span>Light</span></button><button class="hraness-design-theme-toggle__item" type="button" role="menuitemradio" aria-checked="false" data-theme-value="dark"><span data-appearance-icon="dark" aria-hidden="true"></span><span>Dark</span></button><button class="hraness-design-theme-toggle__item" type="button" role="menuitemradio" aria-checked="true" data-theme-value="system"><span data-appearance-icon="system" aria-hidden="true"></span><span>System</span></button></div></div></div></div></header>
<main id="main" class="profile">${body}<aside class="profile-boundary"><h2>What this record tells you</h2><p>Availability records responses within scheduled windows. Capability records exact puzzle results. Neither identifies a model or proves uniqueness, independent operation, or authority. Software keys can be shared; work can be delegated. The issuer signs these claims, and disclosed receipts can be replayed independently.</p><p><a href="https://clankdar.com/docs/#security">Understand the evidence</a></p></aside></main>
<!-- hraness-site-footer -->${supportFooter()}
</div></body></html>`, { headers: {
    "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff",
    "content-security-policy": "default-src 'none'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
    "referrer-policy": "strict-origin-when-cross-origin", "permissions-policy": "camera=(), microphone=(), geolocation=()",
  } });
}

export function renderActorProfile(profile: Record<string, any>): Response {
  const address = String(profile.address);
  const e = profile.evidence ?? {};
  const campaigns = Array.isArray(profile.campaigns) ? profile.campaigns : [];
  const availability = profile.claims?.automatedAvailability;
  const capability = profile.claims?.capability;
  const list = campaigns.length ? `<div class="table-scroll" role="region" aria-label="Recent campaigns" tabindex="0"><table class="profile-table"><caption>Recent campaigns. Every campaign commits to its full schedule before it begins.</caption><thead><tr><th scope="col">Campaign</th><th scope="col">Schedule</th><th scope="col">Responded</th><th scope="col">Missed</th><th scope="col">Passed</th></tr></thead><tbody>${campaigns.map((c: any) => `<tr><th scope="row"><a href="${campaignPath(address, String(c.campaignId))}">${escape(c.policyId)}</a><small>${escape(String(c.campaignId).slice(-8))} · ${c.completedAt ? "Finished" : "In progress"}</small></th><td>${count(c.epochs)} checks</td><td>${count(c.evidence?.completed)}</td><td>${count(c.evidence?.missed)}</td><td>${count(c.evidence?.admitted)}</td></tr>`).join("")}</tbody></table></div>` : `<p class="empty-state">No campaigns yet. Registering a key starts a record; completing scheduled checks adds availability and capability evidence.</p><p><a href="https://clankdar.com/docs/#hosted">Start the first campaign</a></p>`;
  return page("Agent record", `<header class="profile-heading"><h1>An agent’s track record.</h1><p class="profile-address">${escape(address)}</p><p>Key registered ${escape(date(profile.createdAt))}. Private staging · experimental.</p></header>
<section aria-labelledby="evidence-title"><h2 id="evidence-title">Availability and capability, separately.</h2><dl class="record-facts"><div><dt>Availability</dt><dd>${availability ? `${count(availability.completed)} responded · ${count(availability.missed)} missed` : "No scheduled responses yet"}</dd><p>Responses received within their deadline, including failed answers.</p></div><div><dt>Capability</dt><dd>${capability ? `${count(capability.admitted)} of ${count(capability.epochs)} responses passed` : "No capability results yet"}</dd><p>Passing means meeting that campaign’s puzzle policy.</p></div></dl></section>
${count(e.pendingEvidence) ? `<p role="status">${count(e.pendingEvidence)} results are recorded; their receipt publication is pending. Refresh later to check delivery.</p>` : ""}
<section aria-labelledby="campaigns-title"><h2 id="campaigns-title">Campaigns</h2><p>${count(e.campaigns)} committed campaigns. ${count(e.heartbeats)} separate heartbeats; heartbeats are not capability evidence.</p>${list}</section>
<section aria-labelledby="verify-title"><h2 id="verify-title">Inspect the record</h2><p>Public key <code class="wrap-code">${escape(profile.publicKey)}</code></p><p>Signed event ${count(profile.head?.seq)} · <code class="wrap-code">${escape(profile.head?.eventHash ?? "No events")}</code></p><div class="actions"><a href="/v1/actors/${encodeURIComponent(address)}">Profile JSON</a><a href="/v1/actors/${encodeURIComponent(address)}/events">Signed history</a><a href="/v1/issuer">Issuer key</a></div></section>`);
}

export function renderCampaignProfile(campaign: Record<string, any>, address: string, epochs: any[] = []): Response {
  const id = String(campaign.campaignId);
  const e = campaign.evidence ?? {};
  const completed = count(e.completed), missed = count(e.missed), scheduled = count(e.scheduled ?? campaign.epochs);
  const remaining = Math.max(0, scheduled - completed - missed);
  return page("Campaign record", `<header class="profile-heading"><p><a href="${actorPath(address)}">Back to agent record</a></p><h1>${campaign.completedAt ? "A completed campaign." : "A campaign in progress."}</h1><p class="profile-address">${escape(id)}</p><p>${escape(campaign.policyId)} · ${scheduled} scheduled checks · one every ${count(campaign.cadenceSeconds)} seconds · ${count(campaign.windowSeconds)} second window.</p><p>Started ${escape(date(campaign.startsAt))}. ${campaign.completedAt ? `Finished ${escape(date(campaign.completedAt))}.` : "Refresh to see new results."}</p></header>
<section aria-labelledby="outcomes-title"><h2 id="outcomes-title">Every scheduled check counts.</h2><dl class="record-facts"><div><dt>Availability</dt><dd>${completed} responded · ${missed} missed</dd><p>${remaining} checks remain or have an open response window. Misses stay in the record.</p></div><div><dt>Capability</dt><dd>${count(e.admitted)} of ${completed} responses passed</dd><p>${count(e.challengesPassed)} individual puzzles passed. A response can be on time and still fail.</p></div></dl></section>
${count(e.pendingEvidence) ? `<p role="status">${count(e.pendingEvidence)} results are recorded; their receipt publication is pending. Refresh later to check delivery.</p>` : ""}
${epochs.length ? `<section aria-labelledby="receipts-title"><h2 id="receipts-title">Recorded checks</h2><div class="table-scroll" role="region" aria-label="Campaign checks" tabindex="0"><table class="profile-table"><thead><tr><th scope="col">Check</th><th scope="col">Result</th><th scope="col">Evidence</th></tr></thead><tbody>${epochs.map((e: any) => `<tr><th scope="row">${count(e.epoch) + 1}</th><td>${e.status === "missed" ? "Missed" : e.status === "decided" ? (e.verdict ? "Passed" : "Did not pass") : "Awaiting response"}</td><td>${/^[0-9a-f]{64}$/.test(e.evidenceHash ?? e.evidence_hash ?? "") ? `<a href="/v1/evidence/${e.evidenceHash ?? e.evidence_hash}">Signed receipt</a>` : "—"}</td></tr>`).join("")}</tbody></table></div><nav class="actions" aria-label="Check history"><a href="${campaignPath(address, id)}">First checks</a>${typeof campaign.epochsPage?.next === "number" && Number.isSafeInteger(campaign.epochsPage.next) && campaign.epochsPage.next >= 0 ? `<a href="?after=${campaign.epochsPage.next}">Next checks</a>` : ""}</nav></section>` : ""}
<section aria-labelledby="schedule-title"><h2 id="schedule-title">Verify the schedule</h2><p>The issuer committed to the schedule before the first check. When the campaign finishes, the revealed seed lets you reproduce its windows.</p><dl class="schedule-facts"><dt>Schedule commitment</dt><dd><code class="wrap-code">${escape(campaign.scheduleCommit)}</code></dd><dt>Revealed seed</dt><dd><code class="wrap-code">${escape(campaign.scheduleSeed ?? "Published when all checks finish")}</code></dd></dl><div class="actions"><a href="/v1/actors/${encodeURIComponent(address)}/campaigns/${encodeURIComponent(id)}">Campaign JSON</a><a href="/v1/actors/${encodeURIComponent(address)}/events">Signed history</a><a href="/v1/policies/${encodeURIComponent(String(campaign.policyId))}">Puzzle policy</a></div></section>`);
}
